# Reglas de filtro de host para Mini-Burp
# Formato seccionado tipo INI
# Puedes usar wildcards, ej: *.microsoft.com
# También host:puerto, ej: localhost:3000

[settings]
mode=whitelist

[blacklist]

[whitelist]
demo.testfire.net
192.168.26.3:3000

[ignore_paths]
/socket.io/*
*tunnel*
