# Reglas de filtro de host para Mini-Burp
# Formato seccionado tipo INI
# Puedes usar wildcards, ej: *.microsoft.com
# También host:puerto, ej: localhost:3000

[settings]
mode=whitelist

[blacklist]

[whitelist]
192.168.26.2
www.delifrutabolivia.com

[ignore_paths]
/socket.io/*
